/**
 * @file ha_client.h
 * @brief Minimal Home Assistant REST client — read entity state, call a service.
 */
#pragma once
#include <stdbool.h>

/* Ha_state/ha_get_state use Arduino's String, so they're only visible to C++
 * translation units. ui_events.c (plain C, generated by SquareLine) only
 * needs ha_toggle_light(), declared further below with C linkage. */
#ifdef __cplusplus
#include <Arduino.h>

struct Ha_state
{
  bool ok = false;
  String state;
  String unit;
};

/**
 * @brief Reads the current state (and unit_of_measurement attribute, if any) of an entity.
 * @param entity_id Home Assistant entity id, e.g. "sensor.living_room_temperature".
 * @return Ha_state with ok=true on success.
 */
Ha_state ha_get_state(const char* entity_id);

extern "C" {
#endif

/**
 * @brief Calls a Home Assistant service for a single entity (POST /api/services/<domain>/<service>).
 * @param domain Service domain, e.g. "light".
 * @param service Service name, e.g. "toggle".
 * @param entity_id Target entity id.
 * @return true if the request succeeded (HTTP 200).
 */
bool ha_call_service(const char* domain, const char* service, const char* entity_id);

/**
 * @brief Toggles config::ha_light_entity via the "light.toggle" service.
 */
void ha_toggle_light(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif
