// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: HA_HMI

#include "ui.h"
#include "ha_client.h"

void HA_action(lv_event_t * e)
{
	ha_toggle_light();
}
