// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: HA_HMI

#include "ui.h"

void HA_action(lv_event_t * e)
{
	// Your code here
}
