// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: HA_HMI

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_primary[3] = {0x2E2222, 0x2E2222, 0xF7B0B0};
const ui_theme_variable_t _ui_theme_alpha_primary[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_text[3] = {0xF5C6C6, 0xF5C6C6, 0xC7F5C6};
const ui_theme_variable_t _ui_theme_alpha_text[3] = {255, 255, 255};
uint8_t ui_theme_idx = UI_THEME_CIEMNY;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

